name : Update Markdown Formulas

on:
    workflow_dispatch:
        

jobs:
    Update_Formulas:
        runs-on : ubuntu-latest
        steps:
            
            -   uses : denoland/setup-deno@v1
                with :
                    deno-version : 1.23.4
                    
            -   uses : actions/checkout@v3
                
            -   name : Insert Markdown Formulas
                run : 'deno run 
                    --allow-read 
                    --allow-write 
                    --importmap=Tools/Formula/Imports.json
                    Tools/Formula/.js'
                    
            -   name : Commit Inserted Formulas
                uses : EndBug/add-and-commit@v9
                with:
                    default_author : github_actor
                    message : 'Updated Markdown Formulas'
                    add: 'Areas/**'
